export const FUNFACTS = [
  "Der Erfinder: Guglielmo Marconi gilt als Vater des Radios, der 1895 die erste drahtlose Übertragung schaffte und 1901 das erste Signal über den Atlantik sendete.",
  "Nikola Tesla: Er hielt die ersten Radio-Patente, aber Marconi bekam sie später, bis der Oberste Gerichtshof 1943 Teslas Patente bestätigte.",
  "Radiowellen sind keine Schallwellen: Sie sind Teil des elektromagnetischen Spektrums und können durch Wände und Gebäude dringen.",
  "Frühe Downloads: In den frühen 80ern konnte man Videospiele über das Radio herunterladen, eine frühe Form digitaler Datenübertragung.",
  "Eiffelturm gerettet: Seine Funktion als Funkstation verhinderte seinen geplanten Abriss und rettete ihn im Ersten Weltkrieg.",
  '"Soap Opera": Der Begriff stammt von Radiowerbung für Seifenprodukte (Soap), die früher oft als Pausenfüller liefen.',
  "Erste Werbung: Die erste kommerzielle Radiowerbung wurde 1922 gesungen.",
  "Morgenstunden: Der Morgen ist die beliebteste Zeit zum Radiohören, und Menschen hören oft länger Radio am Tag als sie mit ihrem Partner reden.",
  "Reichweite: Radio erreicht nach wie vor riesige Publikumsschichten, auch tief in lokalen Regionen.",
  "Technologie: Radiowellen werden heute auch für Textnachrichten (SMS) und Fernsteuerung (z.B. Autoschlüssel) genutzt.",
  "The BBC began in 1922\nThe BBC has been around for a long - before the television was even invented, in fact! It was established on the 18th of October 1922, as the British Broadcasting Company.  Its mission was to “inform, educate and entertain” - something it still does today!",
  "The BBC was for radio only!\nYou probably get most of your BBC content via the TV or iPlayer, but back in 1922 neither of those things existed! Radio was just beginning to become popular among the public in the early 1920s, with the first ever public British broadcast taking place in 1920. The BBC's broadcasts helped to make radio a more popular medium among the public. The BBC began broadcasting from 2LO, a transmitting station in The Strand in London.",
  "The first BBC programme was a news bulletin\nThe first ever BBC broadcast hit the waves on the 14th of November 1922, less than a month after the company was established! The first programme was a news bulletin. It was read by Arthur Burrows, who was the first Director of Programmes for the BBC.  He read the news and the weather at two different speeds, and listeners were asked which one they preferred.",
  "BBC is nicknamed “Auntie Beeb”\nYou might have heard the BBC called “Auntie” or “Auntie Beeb” before. The nickname came from the fact that the BBC had lots of “aunties” and “uncles”, mainly on its shows Children's Hour. Arthur Burrows was known as “Uncle Arthur” in his broadcasting career! There were others, like Auntie Violet and Uncle Caractacus. It's such a popular nickname that the BBC's annual show of bloopers was called Auntie's Bloomers!",
  "You have to pay a licence fee for the BBC\nThe UK has something called a TV licence, which is a fee you have to pay if you want to watch live and on-demand television. This has been around since the BBC was first established - though in 1922 it cost 10 shillings! Nowadays it will set you back £174.50 per year, and there is a 50% discount for visually impaired people. The fee goes towards funding the BBC, which is one reason why you don't see adverts for other products or services on BBC channels.",
  "The BBC helped shape Britian's sense of time.\nIn the olden days not everywhere agreed on what the time was exactly, and the railways helped to establish an agreed-upon national time. But even then it wasn't uncommon for there to be slight differences in time from town to town. But almost a century after the railways first appeared, the BBC's broadcasts included the first ever transmission of Big Ben striking, and the famous “pips” at the Royal Observatory in Greenwich. These simultaneous broadcasts meant that the UK was truly united in time!",
  "George Orwell worked at the BBC\nEnglish author George Orwell is best known for novels like 1984 and Animal Farm. But not everyone knows that he actually spent some time working for the BBC! Orwell (real name Eric Blair) worked there from 1941 to 1943 for the Empire Service (now called the World Service). He didn't enjoy his time there very much, calling it “something half way between a girl's school and a lunatic asylum”! It is believed that he took inspiration from the BBC in the war years to create his fictional dystopian government in 1984.",
  "Very important news was broken on the BBC first.\nAs the radio was the main source for breaking news from the 1920s to the 1950s, some very important stories showed up on the BBC first. Some of these huge stories include the abdication of Edward VIII in 1936. Edward gave up the crown after less than a year so he could marry American divorcee Wallis Simpson, and he broke the news on a BBC radio broadcast! BBC radio was also where the outbreak of the Second World War was announced in 1939, by then-Prime Minister Neville Chamberlain.",
  "There are some VERY long-running BBC shows!\nThe BBC holds the record of the oldest radio show in the world - The Shipping Forecast has been going since 1924! Interview show Desert Island Discs is still going strong since its first broadcast in 1942 (though the presenter has changed a few times). The longest radio drama of all time is The Archers, which has been on since 1951! The BBC is no slouch in the TV department either! The longest sitcom in the world is the BBC's Last of the Summer Wine, which ran for a staggering 37 years between 1973 and 2010. Other long-running TV show include Match of the Day (which has been going since 1964), Panorama (the longest-running news programme, first broadcast in 1953) and Blue Peter (which first broadcast in1958 and is the longest-running children's programme in the world).",
  "The BBC created the Radio Times\nRadio Times is one of Britain's best-loved magazines - maybe your family always buys the famous Christmas issue! The magazine has been around since 1937, and it was the world's first broadcast listing magazine. It was created by the BBC to print their radio times, but it expanded to television later, and it also has the schedules for other channels. The radio schedule is still published in each edition!",
  "Panorama fooled everyone in 1957\nThe BBC may be our auntie, but she's not above a prank! On the first of April 1957, Panorama featured a report on the “spaghetti harvest”, featuring a “spaghetti tree.” Quite a few viewers fell for the hoax as the segment was presented by Richard Dimbleby, who was a very respected broadcaster! Some viewers called in to point out it was obviously made up, while others asked for advice on how to grow a spaghetti tree! The BBC told them to “place a sprig of spaghetti in a tin of tomato sauce and hope for the best”!",
  "The BBC employs a lot of people. The BBC isn't just one of the biggest media employers in the UK - it's one of the biggest in the world! Over 21,000 people work for the BBC worldwide.",
  "The BBC once reported “no news”. On Good Friday in 1930, the BBC reported on the 8.45pm radio news bulletin: “There is no news.” The rest of the time slot was taken up by piano music!",
  "The BBC had a list of comedy rules:\n1. No burping\n2. No farting\n3. No funny moustaches\n4. NO RUBBER CHICKENS\nIts full title was “The BBC Variety Programmes Policy Guide For Writers and Producers”, and it was a set of guidelines about what you could or couldn't include in your comedy show.",
  "Sir David Attenborough is one of the most influential people in the BBC\nYou'll know Sir David Attenborough as the GOAT when it comes to nature documentaries. You might not know that he's been a part of the BBC for a VERY long time!",
  "The BBC's flagship news programme has been hosted by some of the most illustrious journalists in the corporation's history, starting with Jack de Manio, who presented the first edition in 1957",
  "The broadcast of BBC Radio 4's Today programme is famously one of the official measures the Royal Navy uses to prove that the UK still exists. If it can't be picked up by nuclear submarines during their isolated missions for three days in a row, then it could signify Britain's demise, triggering the doomsday protocol.",
  "In 1988, then Prime Minister Margaret Thatcher famously called the programme from Downing Street after hearing a news bulletin, rather taking presenter John Humphrys by surprise",
  "The airwaves have, on occasion, turned blue, twice because of Jeremy Hunt (although the chancellor has never been the one doing the swearing). But perhaps the moments listeners truly love the most are the times when the usually straight-faced newsreaders can't stop laughing.",
  "2012 rief die UNESCO erstmals den Weltradiotag aus. Er wird seitdem jährlich am 13. Februar gefeiert und steht jedes Jahr unter einem anderen Motto. Damit sollen bestimmte Prinzipien und Werte des Radios und der Arbeit darum wieder mehr in den Fokus der Bevölkerung gebracht werden.",
  "Erfinder des Radios ist der Italiener Guglielmo Marconi, der 1896 ein Patent für einen Apparat für drahtlose Telegrafie anmeldete und die Technologie kurze Zeit später auch demonstrierte. Besonderer Verdienst Marconis lag in der Verbesserung bereits bestehender Komponenten, wodurch er Signale über eine halbe Meile austauschen konnte, sowie eine speziell konstruierte Empfangsantenne. Im Jahr 1902 gelang ihm eine transatlantische Funkübertragung. 1909 erhielt er für seine „Beiträge zur Entwicklung der Telegrafie“ den Physik-Nobelpreis.",
  "Die NASA hat einen eigenen Radiosender. Third Rock Radio spielt einen Mix aus Pop-Rock und Alternative Rock.",
  "Während des Kalten Krieges war das Radio für beide Seiten ein wichtiges Propagandainstrument. Die USA betrieben Radiosender wie Radio Free Europe und Radio Liberty, um den Menschen in Osteuropa eine Alternative zu den staatlich kontrollierten Medien zu bieten. Die Sowjetunion betrieb Radio Moskau, um politische Propaganda zu verbreiten. Der Radiokrieg war ein wichtiger Aspekt des Kalten Krieges, da er den Einfluss der Regierungen auf die öffentliche Meinung verstärkte und den Informationsfluss einschränkte. Er war auch ein Instrument der psychologischen Kriegsführung zur Beeinflussung der Bevölkerung.",
  '<a href="https://open.spotify.com/show/38bCgQdO9YE89ik20YBxDf">Radio Trip Trivia</a>',
  "SHORTER VOICE BREAKS ARE BETTER -- False! Have you always presumed that people switch off after 1:30? RadioAnalyzer compared two 'longer' voice breaks -  3min 30 of presenter musing and people turned OFF.   6min 05 of presenter speaking to listener on phone plus a competition and people tuned IN. It's quality not quantity.",
];

const EMOJIS = ["🤓", "💡", "🧠", "✨", "📌"];

export function insertRandomFunfact(element: HTMLElement) {
  const funfact = FUNFACTS.at(Math.floor(Math.random() * FUNFACTS.length))!;
  const emoji = EMOJIS.at(Math.floor(Math.random() * EMOJIS.length))!;
  element.innerHTML = `<h1>${emoji} Fun fact</h1><div class="quote">${funfact.replaceAll(
    "\n",
    "<br />"
  )}</div>`;
}
